
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffzeuvrgxqdtniizkzmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmemV1dnJneHFkdG5paXprem1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1Njk1NjIsImV4cCI6MjA1ODE0NTU2Mn0.Og3BjVIBf-l4x3TzuU-Qi-w2UxV3R-3b4Gb4NFc_TQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
